### ISSUE TITLE
Can we export these tools to an index.js to embeed with Web requirement

### ISSUE THREAD

**Issue by vncoelho** [rentfuse-labs/neo-wallet-adapter#33] opened 2022-07-18 14:03 UTC
We would like to know the best way to integrate it to an html/js pure website.

**Comment by mfbz** [comment] 2022-07-23 13:29
Possible duplicate of #31.
It would be needed to create a bundled minified version of the packages needed with Webpack or bundler like that.

**Comment by vncoelho** [comment] 2022-07-23 19:01
Thanks, that will be a duplicated.
The title is not the same but result will.

**Closed** 2022-07-23 19:01 UTC
